#!/bin/bash
#
# Check changed js files using jshint and jscs, and sort css using csscomb
#

PATCH_FILE="working-tree.patch"
NPM_BIN="./node_modules/.bin"

function cleanup {
    exit_code=$?
    if [ -f "$PATCH_FILE" ]; then
        git apply "$PATCH_FILE" 2> /dev/null
        rm "$PATCH_FILE"
    fi
    exit $exit_code
}

trap cleanup EXIT SIGINT SIGHUP

# Cancel any changes to the working tree that are not going to be committed
git diff > "$PATCH_FILE"
git checkout -- .

git_cached_js=$(git diff --cached --name-only --diff-filter=ACMR | grep '.js$')
git_cached_css=$(git diff --cached --name-only --diff-filter=ACMR | grep '.css$' | xargs echo)

if [ "$git_cached_js" ]; then
    $NPM_BIN/jshint --reporter node_modules/jshint-stylish/stylish.js $git_cached_js || exit 1
    $NPM_BIN/jscs $git_cached_js || exit 1
fi

# if [ "$git_cached_css" ]; then
#     $NPM_BIN/csscomb -v $git_cached_css
#     git add $git_cached_css
# fi
